/// Generates a nixpkgs-style deps.nix from paket.lock so Nix can build the project
/// reproducibly. Each NuGet package becomes a fetchNuGet entry with an SRI sha512 hash.
module Paket.NixProcess

open System.IO
open System.Text
open Paket
open Paket.PackageSources
open Paket.Logging

/// Renders the deps.nix text. Uses the recorded content hash where present, otherwise
/// computes it on the fly, so this works whether or not 'faket hash' was run first.
let generate (lockFile:LockFile) : string =
    let root = lockFile.RootPath

    let entries =
        [ for KeyValue(groupName, group) in lockFile.Groups do
            for KeyValue(_, pkg) in group.Resolution do
                match pkg.Source with
                | LocalNuGet _ -> ()
                | _ ->
                    let hash =
                        match pkg.ContentHash with
                        | Some h -> Some h
                        | None -> try HashProcess.tryComputeHash root groupName pkg with _ -> None
                    match hash with
                    | Some h -> yield pkg.Name.ToString(), pkg.Version.Normalize(), "sha512-" + h
                    | None -> traceWarnfn "No hash for %O %O - skipped in deps.nix" pkg.Name pkg.Version ]
        |> List.distinctBy (fun (n,v,_) -> n.ToLowerInvariant(), v)
        |> List.sortBy (fun (n,v,_) -> n.ToLowerInvariant(), v)

    let sb = StringBuilder()
    sb.AppendLine "# Generated by 'faket nix'. Consumed by nixpkgs buildDotnetModule (nugetDeps)." |> ignore
    sb.AppendLine "{ fetchNuGet }: [" |> ignore
    for (pname, version, sri) in entries do
        sb.AppendLine(sprintf "  (fetchNuGet { pname = \"%s\"; version = \"%s\"; hash = \"%s\"; })" pname version sri) |> ignore
    sb.AppendLine "]" |> ignore
    sb.ToString()

/// Loads the lock next to the given paket.dependencies and writes deps.nix.
let Run (dependenciesFileName:string) (outputPath:string option) : unit =
    let lockFileName = DependenciesFile.FindLockfile dependenciesFileName
    let lockFile = LockFile.LoadFrom lockFileName.FullName
    let outPath = defaultArg outputPath (Path.Combine(Path.GetDirectoryName lockFileName.FullName, "deps.nix"))
    tracefn "Generating %s from %s" outPath lockFileName.FullName
    File.WriteAllText(outPath, generate lockFile)
    tracefn "Wrote %s" outPath
